### PR TITLE
ci: fix with bumping npm dependencies and removing project .yamlfmt

### PR DESCRIPTION
**Pull request by kachick**
In my environment WSL2 ubuntu and installing https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb, current tests fails with 2 testdata

```
    1) config-none
    2) config-xdg
```

As I understand this results, the test runner unexpectedly respect project [.yamlfmt](https://github.com/bluebrown/vscode-extension-yamlfmt/blob/1c97b2d383f29defc2cc05e8e56c590dbb7ba7ec/.yamlfmt).
So this PR attempt to ignore the file while running tests.

### CODE REVIEW

**Comment by bluebrown** [comment]
Hi, thanks. I am not sure why this file is even there. Maybe we should just delete it. Perhaps we can still keep your code in case it ends up being there.

On the other hand, I dont understand why it doing that. Its been a while since i wrote this, and I recall the test electron instance doing some weird things.

**Comment by kachick** [comment]
Thanks for your reviewing! Using yamlfmt in this repository sounds like a reasonable method for dogfooding. I'm okay for renaming to another path or removing, but I may update this PR if I can make CI success.

**Comment by kachick** [comment]
I have tried to fix CI in my forked repository, the history is 

https://github.com/kachick/vscode-extension-yamlfmt/pull/1
https://github.com/kachick/vscode-extension-yamlfmt/pull/2
https://github.com/kachick/vscode-extension-yamlfmt/pull/3

I chose simplest solution in this PR, just bumping test-electron and removing .yamlfmt

**Comment by kachick** [comment]
Thank you! I'll update #9

**Pull request merged**
