### PR TITLE
feat: support `github-actions-workflow` language

### PR DESCRIPTION
**Pull request by kachick**
This is a restriction from another extension, please see https://github.com/github/vscode-github-actions/issues/195 for further detail.

---

GitHub provides useful extension for GitHub Actions workflow, but [it marks the YAML files as another language](https://github.com/github/vscode-github-actions/blob/02a4f12047a38409abce525e45650235499db371/package.json#L33-L41).

If enabling both their extension and this formatter requires switching the language mode from the VScode UI and switching again to use their extension.
 
After this pull request, the following config enables this formatter while keeping the language ID for GitHub Actions workflows.

```json
{
  "[yaml]": {
    "editor.defaultFormatter": "bluebrown.yamlfmt"
  },
  "[github-actions-workflow]": {
    "editor.defaultFormatter": "bluebrown.yamlfmt"
  }
}
```

I don't think this is a beautiful solution, this means one extension depends on another extension. 
If you know a better way, please close this PR 🙏

### CODE REVIEW

**Comment by bluebrown** [comment]
I think the test is failing because of some other issues. Like described here https://github.com/bluebrown/vscode-extension-yamlfmt/blob/main/MAINTAINER.md#tests. The workflow already runs it twice because the first run would always fail.

Perhaps bumping dependencies, would resolve it.

**Comment by kachick** [comment]
Thanks for your reviewing! I'll check the CI result and attempt to update it in another day. 💪

**Comment by kachick** [comment]
>I think the test is failing because of some other issues. 

>Perhaps bumping dependencies, would resolve it.

Updated in https://github.com/bluebrown/vscode-extension-yamlfmt/pull/8.

**Comment by bluebrown** [comment]
Hi @kachick , thanks alot for all the PRs. I think you have to rebase your branch onto latest main, now.

**Comment by kachick** [comment]
Thank you for reviewing and merging, I have merged current main into this PR. 🙏

**Comment by bluebrown** [comment]
I still need to release it, my token is expired. I will get to it in the next few days. Sorry for the delay.

**Pull request merged**
